insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus', 'STAR.Encompass.Imaging.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus - dev backup', 'STAR.Encompass.Imaging.ServiceBus - dev backup Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus - prod configed', 'STAR.Encompass.Imaging.ServiceBus - prod configed Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.LoanMonitor.ServiceBus', 'STAR.Encompass.LoanMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Enterprise.ServiceBus.Documents', 'STAR.Enterprise.ServiceBus.Documents Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Origination.ConsentMonitor.ServiceBus', 'STAR.Origination.ConsentMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.CCAM.ServiceBus', 'STAR.Originations.CCAM.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.DisclosureMonitor.ServiceBus', 'STAR.Originations.DisclosureMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.Leads.ServiceBus', 'STAR.Originations.Leads.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ODS', 'STAR.Originations.ODS Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus', 'STAR.Originations.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Credit', 'STAR.Originations.ServiceBus.Credit Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Delivery.Review', 'STAR.Originations.ServiceBus.Delivery.Review Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Documents', 'STAR.Originations.ServiceBus.Documents Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Encompass', 'STAR.Originations.ServiceBus.Encompass Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.ERDB', 'STAR.Originations.ServiceBus.ERDB Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.EReport', 'STAR.Originations.ServiceBus.EReport Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.LendingSpace', 'STAR.Originations.ServiceBus.LendingSpace Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.ODS.Leads', 'STAR.Originations.ServiceBus.ODS.Leads Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.VendorServices.ServiceBus', 'STAR.Originations.VendorServices.ServiceBus Notes')
