insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus',                 'SBUS', 'STAR.Encompass.Imaging.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus - dev backup',    'SBUS', 'STAR.Encompass.Imaging.ServiceBus - dev backup Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.Imaging.ServiceBus - prod configed', 'SBUS', 'STAR.Encompass.Imaging.ServiceBus - prod configed Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Encompass.LoanMonitor.ServiceBus',             'SBUS', 'STAR.Encompass.LoanMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Enterprise.ServiceBus.Documents',              'SBUS', 'STAR.Enterprise.ServiceBus.Documents Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Origination.ConsentMonitor.ServiceBus',        'SBUS', 'STAR.Origination.ConsentMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.CCAM.ServiceBus',                 'SBUS', 'STAR.Originations.CCAM.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.DisclosureMonitor.ServiceBus',    'SBUS', 'STAR.Originations.DisclosureMonitor.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.Leads.ServiceBus',                'SBUS', 'STAR.Originations.Leads.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ODS',                             'SBUS', 'STAR.Originations.ODS Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus',                      'SBUS', 'STAR.Originations.ServiceBus Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Credit',               'SBUS', 'STAR.Originations.ServiceBus.Credit Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Delivery.Review',      'SBUS', 'STAR.Originations.ServiceBus.Delivery.Review Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Documents',            'SBUS', 'STAR.Originations.ServiceBus.Documents Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.Encompass',            'SBUS', 'STAR.Originations.ServiceBus.Encompass Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.ERDB',                 'SBUS', 'STAR.Originations.ServiceBus.ERDB Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.EReport',              'SBUS', 'STAR.Originations.ServiceBus.EReport Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.LendingSpace',         'SBUS', 'STAR.Originations.ServiceBus.LendingSpace Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.ServiceBus.ODS.Leads',            'SBUS', 'STAR.Originations.ServiceBus.ODS.Leads Notes')
insert into [Links].[ApplicationLink] ([ApplicationGroupId], [Name], [Notes]) values (7, 'STAR.Originations.VendorServices.ServiceBus',       'SBUS', 'STAR.Originations.VendorServices.ServiceBus Notes')
